//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kondominium_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class cobrosmensalesloggeneracion
    {
        public int LogGeneracionId { get; set; }
        public Nullable<int> Mes { get; set; }
        public Nullable<int> Año { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> PropiedadId { get; set; }
        public Nullable<int> ClienteId { get; set; }
        public string Observacion { get; set; }
    }
}
