//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kondominium_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class cobrosmensalesloggeneracion
    {
        public int LogGeneracionId { get; set; }
        public Nullable<int> Mes { get; set; }
        public Nullable<int> Año { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> PropiedadId { get; set; }
        public Nullable<int> ClienteId { get; set; }
        public string Observacion { get; set; }
    }
}
