//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kondominium_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class configcobrosmensauldet
    {
        public int IdDetalleConf { get; set; }
        public int IdConfig { get; set; }
        public int ProductoId { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<System.DateTime> FechaDeCreacion { get; set; }
        public Nullable<System.DateTime> FechaDeModificacion { get; set; }
        public string CreadoPor { get; set; }
        public string ModificadoPor { get; set; }
        public decimal MTamañoV2 { get; set; }
    
        public virtual configcobrosmensual configcobrosmensual { get; set; }
        public virtual productos productos { get; set; }
    }
}
