//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kondominium_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class contratosdetalle
    {
        public int ContratoId { get; set; }
        public int ProductoId { get; set; }
        public Nullable<decimal> Monto { get; set; }
    
        public virtual contratos contratos { get; set; }
        public virtual productos productos { get; set; }
    }
}
