//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kondominium_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class cuentasporcobrardetalle
    {
        public string VaucherNumber { get; set; }
        public int DetalleId { get; set; }
        public int ProductoId { get; set; }
        public string Descripcion { get; set; }
        public decimal Monto { get; set; }
        public System.DateTime FechaDeCreacion { get; set; }
        public System.DateTime FechaDeModificacion { get; set; }
        public string CreadoPor { get; set; }
        public string ModificadoPor { get; set; }
        public bool Eliminado { get; set; }
    
        public virtual cuentasporcobrar cuentasporcobrar { get; set; }
        public virtual productos productos { get; set; }
    }
}
