//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kondominium_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class cuentasgeneradasdetalleb
    {
        public string PeriodoGenerado { get; set; }
        public int PropiedadId { get; set; }
        public int ClienteId { get; set; }
        public int ProductoId { get; set; }
        public Nullable<decimal> Monto { get; set; }
    }
}
