//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kondominium_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class cuentasporcobrar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cuentasporcobrar()
        {
            this.cuentasporcobrardetalle = new HashSet<cuentasporcobrardetalle>();
        }
    
        public string VaucherNumber { get; set; }
        public int ClienteId { get; set; }
        public int TipoCxC { get; set; }
        public System.DateTime FechaDeEmision { get; set; }
        public System.DateTime FechaDeVencimiento { get; set; }
        public string PeriodoFacturado { get; set; }
        public decimal Total { get; set; }
        public string NPE { get; set; }
        public string BRCode { get; set; }
        public System.DateTime FechaDeCreacion { get; set; }
        public System.DateTime FechaDeModificacion { get; set; }
        public string CreadoPor { get; set; }
        public string ModificadoPor { get; set; }
        public bool Eliminado { get; set; }
    
        public virtual clientes clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cuentasporcobrardetalle> cuentasporcobrardetalle { get; set; }
    }
}
