//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kondominium_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class cuentasporcobrar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cuentasporcobrar()
        {
            this.cuentasporcobrardetalle = new HashSet<cuentasporcobrardetalle>();
        }
    
        public string VaucherNumber { get; set; }
        public int ClienteId { get; set; }
        public string TipoCxC { get; set; }
        public System.DateTime FechaDeEmision { get; set; }
        public System.DateTime FechaDeVencimiento { get; set; }
        public string PeriodoFacturado { get; set; }
        public decimal Total { get; set; }
        public string NPE { get; set; }
        public string BRCode { get; set; }
        public System.DateTime FechaDeCreacion { get; set; }
        public System.DateTime FechaDeModificacion { get; set; }
        public string CreadoPor { get; set; }
        public string ModificadoPor { get; set; }
        public bool Eliminado { get; set; }
        public Nullable<int> Estado { get; set; }
        public Nullable<decimal> Pagado { get; set; }
        public int PropiedadId { get; set; }
    
        public virtual clientes clientes { get; set; }
        public virtual cxctype cxctype { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cuentasporcobrardetalle> cuentasporcobrardetalle { get; set; }
        public virtual propiedades propiedades { get; set; }
    }
}
