//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kondominium_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class errorlog
    {
        public string ApplicationName { get; set; }
        public System.DateTime DateTime { get; set; }
        public string LogType { get; set; }
        public string Message { get; set; }
        public string Exception { get; set; }
        public string Computer { get; set; }
        public string UserId { get; set; }
        public int RowId { get; set; }
        public System.DateTime RowDateTime { get; set; }
    }
}
