//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kondominium_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class errorlog
    {
        public string ApplicationName { get; set; }
        public System.DateTime DateTime { get; set; }
        public string LogType { get; set; }
        public string Message { get; set; }
        public string Exception { get; set; }
        public string Computer { get; set; }
        public string UserId { get; set; }
        public int RowId { get; set; }
        public System.DateTime RowDateTime { get; set; }
    }
}
