//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kondominium_DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KEntities : DbContext
    {
        public KEntities()
            : base("name=KEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<aranceles> aranceles { get; set; }
        public virtual DbSet<clientes> clientes { get; set; }
        public virtual DbSet<cuentasporcobrar> cuentasporcobrar { get; set; }
        public virtual DbSet<cuentasporcobrardetalle> cuentasporcobrardetalle { get; set; }
        public virtual DbSet<empresa> empresa { get; set; }
        public virtual DbSet<poligonos> poligonos { get; set; }
        public virtual DbSet<productos> productos { get; set; }
        public virtual DbSet<propiedades> propiedades { get; set; }
    }
}
