//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kondominium_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class permission
    {
        public int PermissionId { get; set; }
        public string ObjectName { get; set; }
        public string PermissionDesrip { get; set; }
        public int ObjectType { get; set; }
        public Nullable<int> ParentId { get; set; }
    
        public virtual objecttype objecttype1 { get; set; }
    }
}
