//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kondominium_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class propiedades
    {
        public int PropiedadId { get; set; }
        public Nullable<int> TipoDePropiedad { get; set; }
        public string Descripcion { get; set; }
        public string Casa { get; set; }
        public string PoligonoId { get; set; }
        public Nullable<int> ArancelId { get; set; }
        public System.DateTime FechaDeCreacion { get; set; }
        public System.DateTime FechaDeModificacion { get; set; }
        public string CreadoPor { get; set; }
        public string ModificadoPor { get; set; }
    
        public virtual aranceles aranceles { get; set; }
        public virtual poligonos poligonos { get; set; }
    }
}
