//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kondominium_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class propiedades
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public propiedades()
        {
            this.clientepropiedad = new HashSet<clientepropiedad>();
            this.cuentasporcobrar = new HashSet<cuentasporcobrar>();
            this.cuentasporcobrarpago = new HashSet<cuentasporcobrarpago>();
            this.propiedadesdocs = new HashSet<propiedadesdocs>();
            this.calendario = new HashSet<calendario>();
        }
    
        public int PropiedadId { get; set; }
        public Nullable<int> TipoDePropiedad { get; set; }
        public string Descripcion { get; set; }
        public int Casa { get; set; }
        public string PoligonoId { get; set; }
        public Nullable<int> ArancelId { get; set; }
        public System.DateTime FechaDeCreacion { get; set; }
        public System.DateTime FechaDeModificacion { get; set; }
        public string CreadoPor { get; set; }
        public string ModificadoPor { get; set; }
        public bool Eliminado { get; set; }
        public string Senda { get; set; }
        public string Calle { get; set; }
        public string Avenida { get; set; }
        public string CasaLetra { get; set; }
        public string Alameda { get; set; }
        public string PaseoId { get; set; }
        public Nullable<decimal> TamañoV2 { get; set; }
        public Nullable<decimal> ConstruidoM2 { get; set; }
    
        public virtual aranceles aranceles { get; set; }
        public virtual avenida avenida1 { get; set; }
        public virtual calles calles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<clientepropiedad> clientepropiedad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cuentasporcobrar> cuentasporcobrar { get; set; }
        public virtual poligonos poligonos { get; set; }
        public virtual sendas sendas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cuentasporcobrarpago> cuentasporcobrarpago { get; set; }
        public virtual alameda alameda1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<propiedadesdocs> propiedadesdocs { get; set; }
        public virtual paseo paseo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<calendario> calendario { get; set; }
    }
}
