//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kondominium_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class submenupermission
    {
        public int SubMenuPermissionId { get; set; }
        public int SubMenuId { get; set; }
        public string ProfileId { get; set; }
        public int Enabled { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ModifieDate { get; set; }
        public string CreateByUserId { get; set; }
        public string ModifiedByUserId { get; set; }
    }
}
