//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kondominium_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class uploadfiled
    {
        public int UploadFileHId { get; set; }
        public int UploadFileDId { get; set; }
        public string Tipo { get; set; }
        public string Linea { get; set; }
        public string Hora { get; set; }
        public string Fecha { get; set; }
        public string CodigoInterno { get; set; }
        public string Monto { get; set; }
        public string BarraNPE { get; set; }
        public string Banco { get; set; }
        public string FilaTexto { get; set; }
        public string VaucherNumber { get; set; }
        public Nullable<int> Estatus { get; set; }
        public string Mensaje { get; set; }
        public Nullable<System.DateTime> FechaProceso { get; set; }
    
        public virtual uploadfileh uploadfileh { get; set; }
    }
}
