//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kondominium_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwbalance
    {
        public string VaucherNumber { get; set; }
        public Nullable<int> ClienteId { get; set; }
        public string TipoCxC { get; set; }
        public Nullable<System.DateTime> FechaDeEmision { get; set; }
        public Nullable<System.DateTime> FechaDeVencimiento { get; set; }
        public string PeriodoFacturado { get; set; }
        public decimal TotRecibo { get; set; }
        public decimal TotPago { get; set; }
        public string Estado { get; set; }
        public Nullable<int> PropiedadId { get; set; }
    }
}
